[build-system]
requires = ["setuptools>=64", "wheel", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
write_to = "src/napari_segmentation_human_in_loop/_version.py"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
